### ISSUE TITLE
Getting docker-compose.yml invalid error

### ISSUE THREAD

**Issue by ebruengwall-ant** [skalenetwork/skale-node#184]
Some validators getting this error during the node update. 

`2021-01-21 13:56:56,596 - tools.helper - INFO - Running: ['bash', '/tmp/_MEIGFWedU/data/datafiles/update.sh']
2021-01-21 13:56:57,502 - tools.helper - INFO - Removing node containers ...
Removing api, sla, bounty, admin containers ...
2021-01-21 13:56:57,503 - tools.helper - ERROR - Error during shell execution:
2021-01-21 13:56:57,503 - tools.helper - ERROR - The BACKUP_RUN variable is not set. Defaulting to a blank string.
The Compose file '/root/.skale/config/docker-compose.yml' is invalid because:
Unsupported config option for services.advisor: 'cpu_shares'
Unsupported config option for services.skale-admin: 'cpu_shares'
2021-01-21 13:56:57,504 - core.node - ERROR - Update script process errored
Traceback (most recent call last):
  File "core/node.py", line 188, in update
  File "tools/helper.py", line 59, in run_cmd
  File "subprocess.py", line 444, in check_returncode
subprocess.CalledProcessError: Command '['bash', '/tmp/_MEIGFWedU/data/datafiles/update.sh']' returned non-zero exit status 1.`

┆Issue is synchronized with this [Jira Task](https://skalelabs.atlassian.net/browse/SKALE-3792)

**Comment by badrogger** [comment]
They should update docker-compose to 1.27.4 as described here https://skale.network/docs/validators/schain-upgrade
